name: Cleanup - Manual Production Build

on:
  workflow_dispatch:


jobs:
  prod-build:
    uses: cloudsteak/cm-workflows/.github/workflows/production-build-push.yml@1.2.1
    with:
      image_name: lab-cleanup-trigger
      build_context: ./lab-cleanup-trigger
      dockerfile_path: ./lab-cleanup-trigger/Dockerfile
