name: Backend - Manual Production Build

on:
  workflow_dispatch:

jobs:
  prod-build:
    uses: cloudsteak/cm-workflows/.github/workflows/production-build-push.yml@1.2.2
    with:
      image_name: lab-backend