name: Cleanup - Manual Production Build

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Select one of the last 3 tags'
        required: true
        type: string

jobs:
  prod-build:
    uses: cloudsteak/cm-workflows/.github/workflows/production-build-push.yml@1.2.0
    with:
      tag_version: ${{ inputs.tag_version }}
      image_name: lab-cleanup-trigger
      build_context: ./lab-cleanup-trigger
      dockerfile_path: ./lab-cleanup-trigger/Dockerfile
